-- Replace the original NOVA demo services with the public XION medical catalogue.
-- This is a one-time, idempotent content migration; products created by admins are preserved.
UPDATE "Product"
SET "active" = false, "updatedAt" = CURRENT_TIMESTAMP
WHERE "slug" IN ('brand-system', 'digital-experience', 'growth-direction');

INSERT INTO "Product" (
  "id", "title", "slug", "shortDescription", "longDescription", "price", "oldPrice",
  "image", "category", "active", "featured", "sortOrder", "createdAt", "updatedAt"
)
VALUES
  ('xion-product-001', $$Yunona Bio-T halqasimon №1$$, 'yunona-bio-t-halqasimon-1', $$Misli bachadon ichi kontratseptiv vositasi, halqasimon №1 model.$$,
   $$Akusherlik va ginekologiya amaliyoti uchun “Yunona” turkumidagi tibbiy buyum. Mahsulotni tanlash va qo‘llash faqat malakali tibbiyot mutaxassisi tavsiyasi hamda yo‘riqnomasi asosida amalga oshiriladi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//248/694x614/6a05b95564961.png', 'Bachadon ichi vositalari', true, true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-002', $$Yunona Bio-T Ag halqasimon №1$$, 'yunona-bio-t-ag-halqasimon-1', $$Kumush va mis komponentli halqasimon bachadon ichi vositasi.$$,
   $$“Yunona Bio-T Ag” turkumidagi halqasimon tibbiy buyum. Aniq model, o‘lcham va qo‘llash muddati shifokor tomonidan bemorning individual holatiga muvofiq belgilanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//247/694x614/6a05baa93e262.png', 'Bachadon ichi vositalari', true, true, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-003', $$Yunona Bio-T Ag$$, 'yunona-bio-t-ag', $$Kumush qo‘shimchali klassik T-shakldagi bachadon ichi vositasi.$$,
   $$Mis va kumush komponentlari asosidagi “Yunona Bio-T Ag” modeli. Buyum steril qadoqda yetkaziladi; o‘rnatish va nazorat tibbiyot mutaxassisi tomonidan bajarilishi kerak.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//246/694x614/6a05bd03b3ee8.png', 'Bachadon ichi vositalari', true, true, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-004', $$Yunona Bio-T$$, 'yunona-bio-t', $$Misli klassik T-shakldagi bachadon ichi kontratseptiv vositasi.$$,
   $$“Yunona Bio-T” tibbiy plastmassa va mis komponentlari asosida ishlab chiqarilgan. Mahsulotni qo‘llashdan oldin yo‘riqnoma, qarshi ko‘rsatmalar va shifokor tavsiyasi bilan tanishish zarur.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//245/694x614/6a05bdcba2dbf.png', 'Bachadon ichi vositalari', true, true, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-005', $$Yunona Bio Multi Ag$$, 'yunona-bio-multi-ag', $$Kumush qo‘shimchali ko‘p tayanchli bachadon ichi vositasi.$$,
   $$“Yunona Bio Multi Ag” individual anatomik xususiyatlarni hisobga olgan holda mutaxassis tanlovi uchun mo‘ljallangan. O‘rnatish faqat tibbiy muassasada amalga oshiriladi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//244/694x614/6a05c2b119303.png', 'Bachadon ichi vositalari', true, true, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-006', $$Yunona Bio Multi$$, 'yunona-bio-multi', $$Ko‘p tayanchli misli bachadon ichi kontratseptiv vositasi.$$,
   $$“Yunona Bio Multi” modeli professional ginekologik amaliyot uchun mo‘ljallangan. Qo‘llash imkoniyati, muddati va keyingi nazorat shifokor tomonidan belgilanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//243/694x614/6a05c39594feb.png', 'Bachadon ichi vositalari', true, false, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-007', $$Yunona Bio-T Ag halqasimon №2$$, 'yunona-bio-t-ag-halqasimon-2', $$Kumush va mis komponentli halqasimon №2 bachadon ichi vositasi.$$,
   $$Halqasimon №2 “Yunona Bio-T Ag” modeli. Mahsulot faqat mutaxassis tomonidan tanlanadi, o‘rnatiladi va nazorat qilinadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//182/694x614/6a05c49216c9a.png', 'Bachadon ichi vositalari', true, false, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-008', $$Yunona Bio-T Super$$, 'yunona-bio-t-super', $$Propolisli antimikrob tarkib bilan ishlov berilgan misli T-shakldagi vosita.$$,
   $$“Yunona Bio-T Super” — propolis saqlovchi tarkib bilan maxsus ishlov berilgan, nominal faol mis yuzasi 380 mm² bo‘lgan steril tibbiy buyum. Kontratseptsiya muddati 5 yilgacha; faqat shifokor tavsiyasi bilan qo‘llanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//180/694x614/6a0594844b368.png', 'Bachadon ichi vositalari', true, true, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-009', $$Juno Gold$$, 'juno-gold', $$Oltin va mis komponentli premium bachadon ichi vositasi.$$,
   $$“Juno Gold” professional ginekologik amaliyot uchun mo‘ljallangan bachadon ichi kontratseptiv vositasidir. Moslik va qo‘llash tartibini tibbiyot mutaxassisi belgilaydi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//175/694x614/6a0597e5e98aa.png', 'Bachadon ichi vositalari', true, true, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-010', $$Yunona Bio-T halqasimon №2$$, 'yunona-bio-t-halqasimon-2', $$Misli halqasimon №2 bachadon ichi kontratseptiv vositasi.$$,
   $$“Yunona Bio-T” halqasimon №2 modeli. Tibbiy buyumni tanlash, o‘rnatish va chiqarish faqat malakali mutaxassis tomonidan amalga oshiriladi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//264/694x614/6a05983f76ef8.png', 'Bachadon ichi vositalari', true, false, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('xion-product-011', $$Doktor Juravlev sferik uroginekologik pessariysi$$, 'juravlev-sferik-pessariy', $$Uroginekologik amaliyot uchun sferik shakldagi silikon pessariy.$$,
   $$Tibbiy silikondan tayyorlangan sferik pessariy. Kerakli o‘lcham va qo‘llash sxemasi klinik ko‘rikdan so‘ng shifokor tomonidan tanlanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//258/694x614/6a03106488299.png', 'Ginekologik pessariylar', true, true, 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-012', $$Silikon kosachasimon perforatsiyali pessariy$$, 'silikon-kosachasimon-perforatsiyali-pessariy', $$Kosachasimon va perforatsiyali tibbiy silikon pessariy.$$,
   $$Ginekologik amaliyot uchun yumshoq tibbiy silikondan tayyorlangan pessariy. Model va o‘lchamni shifokor individual tanlaydi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//257/694x614/6a031775ade08.png', 'Ginekologik pessariylar', true, false, 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-013', $$Silikon kosacha-uretral pessariy$$, 'silikon-kosacha-uretral-pessariy', $$Kosachasimon-uretral shakldagi qo‘llab-quvvatlovchi pessariy.$$,
   $$Uroginekologik ko‘rsatmalar bo‘yicha qo‘llash uchun ishlab chiqarilgan tibbiy silikon buyum. Faqat mutaxassis tanlovi va nazorati ostida qo‘llanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//256/694x614/6a031dc52b459.png', 'Ginekologik pessariylar', true, false, 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-014', $$Silikon Hodge pessariysi$$, 'silikon-hodge-pessariy', $$Hodge shaklidagi qo‘llab-quvvatlovchi tibbiy silikon pessariy.$$,
   $$Professional ginekologik amaliyot uchun mo‘ljallangan Hodge shaklidagi pessariy. O‘lcham va foydalanish davomiyligi shifokor tomonidan belgilanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//255/694x614/6a0320aaa6045.png', 'Ginekologik pessariylar', true, false, 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-015', $$Silikon uretral pessariy$$, 'silikon-uretral-pessariy', $$Uretral qo‘llab-quvvatlash uchun mo‘ljallangan silikon pessariy.$$,
   $$Tibbiy silikondan ishlab chiqarilgan uroginekologik buyum. Mahsulot shakli va o‘lchami klinik ehtiyoj asosida mutaxassis tomonidan tanlanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//254/694x614/6a032233690f0.png', 'Ginekologik pessariylar', true, false, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-016', $$Silikon kubik perforatsiyali pessariy$$, 'silikon-kubik-perforatsiyali-pessariy', $$Perforatsiyali kubik shakldagi qo‘llab-quvvatlovchi pessariy.$$,
   $$Ginekologik amaliyotda individual ko‘rsatma bo‘yicha qo‘llanadigan tibbiy silikon pessariy. Foydalanish shifokor nazoratini talab qiladi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//253/694x614/6a0323c456313.png', 'Ginekologik pessariylar', true, false, 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-017', $$Yunona bachadon pessariylari$$, 'yunona-bachadon-pessariylari', $$Professional tanlash uchun “Yunona” bachadon pessariylari turkumi.$$,
   $$Turli klinik holatlar uchun mo‘ljallangan “Yunona” pessariylari. Mos model va o‘lcham tibbiyot mutaxassisi tomonidan tanlanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//250/694x614/6a030f6bcfe31.png', 'Ginekologik pessariylar', true, false, 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-018', $$Silikon qo‘ziqorinsimon pessariy$$, 'silikon-qoziqorinsimon-pessariy', $$Qo‘ziqorinsimon shakldagi qo‘llab-quvvatlovchi silikon pessariy.$$,
   $$Tibbiy silikondan tayyorlangan ginekologik pessariy. Qo‘llash faqat ko‘rik va mutaxassis tavsiyasidan keyin amalga oshiriladi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//251/694x614/6a03254fd6ec3.png', 'Ginekologik pessariylar', true, true, 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-019', $$Silikon qalin halqa pessariy$$, 'silikon-qalin-halqa-pessariy-simurg', $$Qalin halqa shaklidagi qo‘llab-quvvatlovchi silikon pessariy.$$,
   $$“Simurg” tibbiy silikonidan tayyorlangan qalin halqa modeli. O‘lcham va qo‘llash rejimi shifokor tomonidan belgilanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//252/694x614/6a0326bcc51b7.png', 'Ginekologik pessariylar', true, false, 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-020', $$Silikon halqa pessariy$$, 'silikon-halqa-pessariy', $$Klassik halqa shaklidagi tibbiy silikon pessariy.$$,
   $$Ginekologik amaliyot uchun halqa shaklidagi silikon buyum. To‘g‘ri o‘lchamni shifokor ko‘rik asosida tanlaydi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//265/694x614/6a032cdda8dbb.png', 'Ginekologik pessariylar', true, false, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-021', $$Silikon qalin halqa pessariy$$, 'silikon-qalin-halqa-pessariy', $$Qalin halqa konstruksiyasidagi tibbiy silikon pessariy.$$,
   $$Qo‘llab-quvvatlovchi qalin halqa modeli. Mahsulot faqat tibbiyot mutaxassisi tavsiyasi va nazorati ostida qo‘llanadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//266/694x614/6a032f80ce934.png', 'Ginekologik pessariylar', true, false, 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

  ('xion-product-022', $$Cusco Premium ginekologik ko‘zgusi$$, 'cusco-premium-ginekologik-kozgu', $$1/S, 2/M va 3/L o‘lchamlaridagi bir martalik ginekologik ko‘zgu.$$,
   $$Professional ko‘riklar uchun Cusco turidagi Premium ginekologik ko‘zgu. Mavjud o‘lcham va qadoqlash tafsilotlarini operator orqali aniqlashtiring.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//203/694x614/6a04c8feb655d.png', 'Ginekologik ko‘zgu va to‘plamlar', true, true, 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-023', $$Yunona Classic Combi aspiratsion zondi №051$$, 'yunona-classic-combi-aspiratsion-zond-051', $$Namuna olish uchun Classic Combi aspiratsion zondi.$$,
   $$Akusherlik va ginekologik amaliyotda professional foydalanish uchun bir martalik “Yunona” zondi. Tibbiy muassasalar uchun yetkazib beriladi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//237/694x614/6a02b41b6438a.png', 'Bir martalik asboblar', true, false, 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-024', $$Yunona Classic aspiratsion zondi №048$$, 'yunona-classic-aspiratsion-zond-048', $$Professional namuna olish uchun Classic aspiratsion zondi.$$,
   $$Bir martalik “Yunona Classic” zondi diagnostik material olish uchun mo‘ljallangan. Faqat malakali tibbiyot xodimi foydalanishi kerak.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//235/694x614/6a02b9dec2036.png', 'Bir martalik asboblar', true, false, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-025', $$Yunona Profi Combi aspiratsion zondi №050$$, 'yunona-profi-combi-aspiratsion-zond-050', $$Professional kombinatsiyalangan aspiratsion zond.$$,
   $$“Yunona Profi Combi” bir martalik tibbiy asbobi klinik diagnostika jarayonlari uchun mo‘ljallangan. Qo‘llash yo‘riqnomasiga rioya qilish zarur.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//236/694x614/6a02b26ea9051.png', 'Bir martalik asboblar', true, false, 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-026', $$Yunona Profi aspiratsion zondi №049$$, 'yunona-profi-aspiratsion-zond-049', $$Professional ginekologik aspiratsion zond.$$,
   $$“Yunona Profi” bir martalik zondi tibbiy muassasalardagi diagnostika amaliyoti uchun mo‘ljallangan. Mutaxassis foydalanishi talab qilinadi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//234/694x614/6a02b81f705d1.png', 'Bir martalik asboblar', true, false, 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-027', $$Eyre ginekologik shpateli №021$$, 'eyre-ginekologik-shpatel-021', $$Sitologik namuna olish uchun bir martalik Eyre shpateli.$$,
   $$Ginekologik diagnostika amaliyotida material olish uchun mo‘ljallangan bir martalik asbob. Professional foydalanish uchun.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//233/694x614/6a02c1a7be8d8.png', 'Bir martalik asboblar', true, false, 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-028', $$Volkmann ginekologik qoshiqchasi №022$$, 'volkmann-ginekologik-qoshiqcha-022', $$Diagnostik material olish uchun Volkmann ginekologik qoshiqchasi.$$,
   $$Professional ginekologik ko‘rik va namuna olish jarayonlari uchun bir martalik tibbiy asbob.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//232/694x614/6a02c285a2eb1.png', 'Bir martalik asboblar', true, false, 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-029', $$Universal floklangan zond №266$$, 'universal-floklangan-zond-266', $$Biologik namuna olish uchun universal floklangan zond.$$,
   $$Laboratoriya va klinik diagnostika uchun floklangan ishchi qismga ega bir martalik universal zond. Professional foydalanish uchun.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//231/694x614/6a02c6931f7c1.png', 'Bir martalik asboblar', true, false, 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-030', $$Yunona tampon zondi №042$$, 'yunona-tampon-zond-042', $$Tamponli ishchi qismga ega bir martalik diagnostik zond.$$,
   $$Klinik namuna olish uchun mo‘ljallangan “Yunona” bir martalik tibbiy asbobi. Mutaxassis foydalanishi uchun.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//230/694x614/6a02c8eed90c9.png', 'Bir martalik asboblar', true, false, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-031', $$Yunona urogenital tamponli zondi №047$$, 'yunona-urogenital-tamponli-zond-047', $$Urogenital va tamponli kombinatsiyalangan diagnostik zond.$$,
   $$Urogenital namuna olish uchun bir martalik kombinatsiyalangan “Yunona” zondi. Faqat professional tibbiy foydalanish uchun.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//229/694x614/6a02cc06ce3df.png', 'Bir martalik asboblar', true, false, 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-032', $$Yunona urogenital zondi №041$$, 'yunona-urogenital-zond-041', $$Urogenital namuna olish uchun bir martalik zond.$$,
   $$Klinik diagnostika jarayonlarida urogenital material olish uchun mo‘ljallangan “Yunona” zondi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//228/694x614/6a02d128b2c62.png', 'Bir martalik asboblar', true, false, 32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-033', $$Yunona sitoshyotka va shpatelli zondi №043$$, 'yunona-sitoshyotka-shpatelli-zond-043', $$Sitoshyotka va shpatelni birlashtirgan diagnostik zond.$$,
   $$Sitologik material olish uchun ikki ishchi qismli bir martalik “Yunona” asbobi. Professional foydalanish uchun.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//227/694x614/6a02d345e4455.png', 'Bir martalik asboblar', true, false, 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-034', $$Yunona sitoshyotka va tamponli zondi №045$$, 'yunona-sitoshyotka-tamponli-zond-045', $$Sitoshyotka va tamponli kombinatsiyalangan diagnostik zond.$$,
   $$Klinik namuna olish uchun sitoshyotka va tamponni birlashtirgan bir martalik “Yunona” tibbiy asbobi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//226/694x614/6a02d8a187b44.png', 'Bir martalik asboblar', true, false, 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-035', $$Yunona servikal shyotka va tamponli zondi №046$$, 'yunona-servikal-shyotka-tamponli-zond-046', $$Servikal shyotka va tamponli kombinatsiyalangan zond.$$,
   $$Servikal material olish uchun ikki ishchi qismli bir martalik “Yunona” tibbiy asbobi. Professional foydalanish uchun.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//225/694x614/6a02de187371a.png', 'Bir martalik asboblar', true, false, 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-036', $$Yunona sitoshyotka va servikal shyotkali zondi №044$$, 'yunona-sitoshyotka-servikal-shyotkali-zond-044', $$Ikki xil shyotkali kombinatsiyalangan diagnostik zond.$$,
   $$Sitologik va servikal material olish uchun mo‘ljallangan bir martalik kombinatsiyalangan “Yunona” tibbiy asbobi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//224/694x614/6a02df02813c7.png', 'Bir martalik asboblar', true, false, 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-037', $$Yunona servikal shyotka kombinatsiyalangan Plus №225$$, 'yunona-servikal-shyotka-kombinatsiyalangan-plus-225', $$Plus turidagi kombinatsiyalangan servikal shyotka.$$,
   $$Professional sitologik namuna olish uchun ishlab chiqilgan bir martalik “Yunona” servikal shyotkasi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//223/694x614/6a02e1ae06a07.png', 'Bir martalik asboblar', true, false, 37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-038', $$Yunona servikal shyotka Plus №224$$, 'yunona-servikal-shyotka-plus-224', $$Plus turidagi bir martalik servikal shyotka.$$,
   $$Servikal material olish uchun mo‘ljallangan “Yunona” bir martalik tibbiy asbobi. Professional foydalanish uchun.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//222/694x614/6a02e30656ca8.png', 'Bir martalik asboblar', true, false, 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-039', $$Yunona servikal shyotka kombinatsiyalangan №219$$, 'yunona-servikal-shyotka-kombinatsiyalangan-219', $$Kombinatsiyalangan servikal diagnostik shyotka.$$,
   $$Klinik sitologik namuna olish uchun bir martalik kombinatsiyalangan “Yunona” servikal shyotkasi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//221/694x614/6a02e45ce556c.png', 'Bir martalik asboblar', true, false, 39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-040', $$Yunona servikal shyotka №040$$, 'yunona-servikal-shyotka-040', $$Servikal namuna olish uchun bir martalik diagnostik shyotka.$$,
   $$Professional ginekologik diagnostika uchun mo‘ljallangan “Yunona” servikal shyotkasi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//220/694x614/6a02f042bcbff.png', 'Bir martalik asboblar', true, false, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-041', $$Yunona sitoshyotka Plus №039$$, 'yunona-sitoshyotka-plus-039', $$Plus turidagi bir martalik sitologik shyotka.$$,
   $$Klinik sitologik material olish uchun mo‘ljallangan “Yunona” bir martalik tibbiy asbobi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//219/694x614/6a02fa2b99099.png', 'Bir martalik asboblar', true, false, 41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-042', $$Yunona sitoshyotka №038$$, 'yunona-sitoshyotka-038', $$Sitologik namuna olish uchun bir martalik shyotka.$$,
   $$Ginekologik sitologik material olish uchun mo‘ljallangan “Yunona” bir martalik diagnostik asbobi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//218/694x614/6a02fb278a6d8.png', 'Bir martalik asboblar', true, false, 42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-043', $$DILASIM gigroskopik servikal kengaytirgichi$$, 'dilasim-servikal-kengaytirgich', $$Servikal kanal uchun gigroskopik tibbiy kengaytirgich.$$,
   $$DILASIM professional akusherlik-ginekologik amaliyot uchun mo‘ljallangan gigroskopik servikal kengaytirgichdir. Faqat tibbiyot mutaxassisi qo‘llashi kerak.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//202/694x614/690b26da9f11d.png', 'Servikal kengaytirgichlar', true, false, 43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-044', $$Yunona laminariya tayoqchalari to‘plami$$, 'yunona-laminariya-tayoqchalari', $$Professional akusherlik amaliyoti uchun laminariya tayoqchalari to‘plami.$$,
   $$Servikal tayyorlash jarayonlari uchun mo‘ljallangan “Yunona” laminariya tayoqchalari. To‘plamdan faqat malakali tibbiyot xodimi foydalanishi kerak.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//201/694x614/690b2716977c9.png', 'Servikal kengaytirgichlar', true, false, 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-product-045', $$ColpoTrain® vaginal konuslar to‘plami №175$$, 'colpotrain-vaginal-konuslar-175', $$Mushaklarni mashq qildirish uchun bosqichli vaginal konuslar to‘plami.$$,
   $$ColpoTrain® vaginal konuslar to‘plami shifokor tavsiyasi asosidagi individual mashqlar uchun mo‘ljallangan. Qo‘llash sxemasi va qarshi ko‘rsatmalar mutaxassis bilan aniqlashtiriladi.$$, NULL, NULL,
   'https://xion.uz/data/uploads/module/shop/products//200/694x614/690b27967de83.png', 'Reabilitatsiya buyumlari', true, true, 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO UPDATE SET
  "title" = EXCLUDED."title",
  "shortDescription" = EXCLUDED."shortDescription",
  "longDescription" = EXCLUDED."longDescription",
  "price" = EXCLUDED."price",
  "oldPrice" = EXCLUDED."oldPrice",
  "image" = EXCLUDED."image",
  "category" = EXCLUDED."category",
  "active" = EXCLUDED."active",
  "featured" = EXCLUDED."featured",
  "sortOrder" = EXCLUDED."sortOrder",
  "updatedAt" = CURRENT_TIMESTAMP;

-- Keep NOVA as the public brand while replacing its business/contact content.
INSERT INTO "SiteSetting" ("id", "key", "value", "createdAt", "updatedAt")
VALUES
  ('xion-setting-company', 'company', '{"name":"NOVA","descriptor":"Ayollar salomatligi uchun tibbiy buyumlar"}'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-setting-hero', 'hero', '{"eyebrow":"NOVA · RASMIY TIBBIY YECHIMLAR","title":"Ayollar salomatligi uchun ishonchli tibbiy buyumlar","subtitle":"Akusherlik, ginekologiya va urologiya uchun mahsulotlar. O‘zbekiston bo‘ylab yetkazib berish va mutaxassis yordami.","primaryCta":"Katalogni ko‘rish","secondaryCta":"Mutaxassis bilan bog‘lanish"}'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-setting-contact', 'contact', '{"phone":"+998 99 556 06 60","phones":["+998 99 556 06 60","+998 71 230 04 40","+998 88 159 05 50"],"email":"info@xion.uz","emails":[{"label":"Umumiy savollar","value":"info@xion.uz"},{"label":"Savdo bo‘limi","value":"sales@xion.uz"},{"label":"Ofis","value":"office@xion.uz"}],"telegramUrl":"https://t.me/xionuzb","address":"Toshkent shahri, Olmazor tumani, Allon ko‘chasi 141A","workingHours":"Dushanba–Juma, 08:00–17:00"}'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-setting-stats', 'stats', '[{"value":"10+","label":"yillik tajriba"},{"value":"45+","label":"katalog mahsuloti"},{"value":"25+","label":"eksport mamlakati"}]'::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("key") DO UPDATE SET
  "value" = EXCLUDED."value",
  "updatedAt" = CURRENT_TIMESTAMP;

UPDATE "Advertisement"
SET "enabled" = false, "updatedAt" = CURRENT_TIMESTAMP
WHERE "title" = 'Yozgi strategiya sessiyasi';

INSERT INTO "Advertisement" (
  "id", "title", "description", "image", "ctaLabel", "ctaUrl", "placement",
  "startAt", "endAt", "enabled", "sortOrder", "createdAt", "updatedAt"
)
VALUES
  ('xion-hero-medical-catalog', $$Ayollar salomatligi uchun tibbiy buyumlar$$,
   $$Akusherlik, ginekologiya va urologiya yo‘nalishlari uchun ishonchli mahsulotlar katalogi.$$,
   'https://xion.uz/data/uploads/module/structure/84/37/6a219c2ea8abd.webp', 'Katalogni ko‘rish', '#products', 'HERO', NULL, NULL, true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('xion-campaign-official-supply', $$Simurg mahsulotlari O‘zbekiston bo‘ylab$$,
   $$Sertifikatlangan tibbiy buyumlar, B2B buyurtmalar va mutaxassis bilan bevosita maslahat.$$,
   'https://xion.uz/data/uploads/module/shop/products//175/694x614/6a0597e5e98aa.png', 'Buyurtma qoldirish', '#products', 'AFTER_HERO', NULL, NULL, true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
